version: "3.9"
services:
 dbpost:
  image: postgres:latest
  environment:
   POSTGRES_DB: db_wholesale
   POSTGRES_USER: joel
   POSTGRES_PASSWORD: 1337
  volumes:
   - "./script.sql:/docker-entrypoint-initdb.d/init.sql"
  ports:
   - 5432:5432
